### ISSUE TITLE
add some python packages in python3_scientific (from pypi)

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#127]
- [x] basemap
- [x] cdsapi
- [x] Fiona
- [x] pandas
- [x] pygraphviz
- [x] graphviz
- [x] scikit-learn

**Comment by thebaptiste** [comment]
There is a difficulty with basemap. This package has non entry in https://pypi.org/simple/basemap/ because it is too big (about 130 Mo, see [here](https://github.com/matplotlib/matplotlib/issues/5655).
So `pip install basemap` doesn't work, we must install it specifying directly the tar.gz url in requirements3.txt : https://downloads.sourceforge.net/project/matplotlib/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz#egg=basemap
I had to add downloads.sourceforge.net in trusted-host for pip install to work behind our proxy at Meteo-France.
See [PR](https://github.com/metwork-framework/mfext/pull/129) adding the possibility to pip install a package from https url outside pypi.org

**Comment by thebaptiste** [comment]
graphviz and pygraphviz need rpm graphviz-devel (and dependencies) to be installed.
We will build graphviz in scientific layer.

**Comment by thebaptiste** [comment]
Done (for python3_scientific **and** python2_scientific) for : 
* basemap
* cdsapi
* pandas
* graphviz
* scikit-learn

Not done for : 
* Fiona : doesn't build on CentOS6 with gcc 4.4.7 (have to try with scl)
* pygraphviz : needs graphviz and graphviz-devel rpms to build, we will build graphviz in scientific layer

**Comment by thebaptiste** [comment]
Done for pygraphviz
Still missing Fiona

**Comment by thebaptiste** [comment]
Done for Fiona
