### ISSUE TITLE
chmod/chown failed while removing module

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1569]
## Problem

I face a `chmod/chown: failed...` error message while removing a metwork module:

```
[...]
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                         1/1 
  Erasing          : metwork-mfserv-full-10:2.1.ci891.b3046ae-1378.gen.x86_64                                                                                                1/4 
  Erasing          : metwork-mfserv-10:2.1.ci891.b3046ae-1378.gen.x86_64                                                                                                     2/4 
  Erasing          : metwork-mfserv-layer-nodejs-2.1-10:2.1.ci891.b3046ae-1378.gen.x86_64                                                                                    3/4 
  Erasing          : metwork-mfserv-2.1-10:2.1.ci891.b3046ae-1378.gen.x86_64                                                                                                 4/4 
  Running scriptlet: metwork-mfserv-2.1-10:2.1.ci891.b3046ae-1378.gen.x86_64                                                                                                 4/4 
chmod: failed to get attributes of '/home/mfserv': No such file or directory
chown: failed to get attributes of '/home/mfserv': No such file or directory
```

Way to reproduce:
```
docker run -it metwork/mfservplugins-centos8-buildimage:release_2.1
yum remove metwork-mfserv
```

## Analysis

**Removing** deletes the directory `/home/mfserv` before the post-uninstallation, where the chmod/chown is tried.

I think this is the **update** which saves it.

## Proposed solution

in [adm/_metwork.spec](https://github.com/metwork-framework/mfext/blob/master/adm/_metwork.spec) :
```
chmod --reference=/home/{{MFMODULE_LOWERCASE}} /home/.home_{{MFMODULE_LOWERCASE}}.perm 2>/dev/null
chown --reference=/home/{{MFMODULE_LOWERCASE}} /home/.home_{{MFMODULE_LOWERCASE}}.perm 2>/dev/null
```
or (move it after directory test)
```
if test -d /home/{{MFMODULE_LOWERCASE}}; then
    touch /home/.home_{{MFMODULE_LOWERCASE}}.perm
    chmod --reference=/home/{{MFMODULE_LOWERCASE}} /home/.home_{{MFMODULE_LOWERCASE}}.perm
    chown --reference=/home/{{MFMODULE_LOWERCASE}} /home/.home_{{MFMODULE_LOWERCASE}}.perm
```

**Comment by thebaptiste** [comment]
More that the error message which is easy to fix, I don't understand why this is happening for mfserv and mfbase, but not for mfdata.
The saving of `/home/<module>` on `/home/<module>.rpmsave<date>` seems also being working only for mfdata

**Comment by thebaptiste** [comment]
Ok. I understood. Your test is in a very special case that should almost never happen : you remove the rpm `metwork-mfserv` while `/home/mfserv` is completely empty. If you had logged once as user `mfserv` or started `mfserv` in your container, `/home/mfserv` would not be empty and everything will be fine (no error message while uninstalling the rpm and saving of `/home/mfserv` ok).
There is no such problem with mfdata because `/home/mfdata/var/in` is created when installing the rpm and so `/home/mfdata` is not empty.
If you explicitely uninstall `metwork-mfserv-2.1` before `metwork-mfserv` there will be no problem either.

So I'm ok to redirect the outputs of the two incriminated commands on `/dev/null` to prevent error messages for this very special case.
