### ISSUE TITLE
add make in mfext

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfext#1690]
`make` is not provided by mfext whereas it is an essential tool for metwork. (in our company we have servers delivered with metwork installed but without make)

**Comment by thebaptiste** [comment]
Done by #1691 

I can backport in releases if helpful. Which ones ?

**Comment by matthieumarrast** [comment]
I would say, from **release_1.1**, the first version with a Python (3.8) version still supported as per https://devguide.python.org/versions/

**Comment by thebaptiste** [comment]
I don't want to encourage the use of old Metwork releases. So I will do it for 2.1, 2.0 and maybe 1.2.

**Comment by thebaptiste** [comment]
Anyway, for a previoulsy installed release of mfext, an admin action is necessary to install make. There is not a big difference between updating mfext and installing make directly...  except it's much faster to install make directly !
Updating mfext just in order to install make would be like using a sledgehammer to crack a nut...

**Comment by matthieumarrast** [comment]
`make` has been added as a dependency, as a result `make` will be installed while installing metwork.
