### ISSUE TITLE
add python3 support for eccodes

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#79]
it should work with the new 2.9 version

**Comment by thebaptiste** [comment]
It seems to be impossible with eccodes version 2.9.0 or 2.9.2, because of the usage of swig typemaps for numpy and gribapi (eccodes files numpy.i, gribapi_swig.i and swig_wrap_numpy.c), not compatible with python3. The build is ok but it fails at runtime, "import eccodes" brings the following message 
>>> 
ImportError: /opt/metwork/mfext/build/opt/python3_scientific/lib/python3.5/site-packages/gribapi/_gribapi_swig.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyString_AsString
>>> 

Maybe we could try to build last version of swig inside mfext but I don't think it will solve the problem (see : http://www.swig.org/Doc3.0/Python.html#Python_python3support)

Try to use py3c (https://py3c.readthedocs.io/en/latest/index.html) would probably be a better idea.

**Comment by thefab** [comment]
reply for ecmwf:

https://jira.ecmwf.int/browse/SUP-2645

"This is definitely happening! And we are working on it as we speak. We cannot commit to any specific date but I think this should be available in the short term."

So python3 is not supported in eccodes 2.9.2 for the moment

**Comment by thebaptiste** [comment]
New reply from ECMWF : resolved in release 2.10.0 (available)
