### ISSUE TITLE
in plugin python requirements support git+ssh without -e

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#798]
`-e git+ssh://git@github.com/...` => ok
`git+ssh://git@github.com/...` => not ok

**Comment by thebaptiste** [comment]
Could you provide an example with `git+ssh` ? I only have examples with `git+https`...

**Comment by thebaptiste** [comment]
With `git+ssh` it also only works with `-e`. The reason it apparently that without `-e`, `install_requirements` set `export https_proxy=http://127.0.0.1:9999`, and it blocks autodownload. I don't understand exactly why, but with `-e git+https` there is no problem (no autodownload needed).

**Comment by thebaptiste** [comment]
When calculating `requirements3.txt` from `requirements-to-freeze.txt` 
- `-e git+https://github.com/metwork-framework/xattrfile.git#egg=xattrfile` becomes something like `-e git+https://github.com/metwork-framework/xattrfile.git@db24341265249b3b0bf4f89604e05cea3743374b#egg=xattrfile
`
- `git+https://github.com/metwork-framework/xattrfile.git#egg=xattrfile` becomes `xattrfile==0.0.1` which is not found because not existing on pypi

**Comment by thebaptiste** [comment]
If we change `install_requirements` to do the same thing for `^git` than for `^-e git` and if we directly set `git+https://github.com/metwork-framework/xattrfile.git@db24341265249b3b0bf4f89604e05cea3743374b#egg=xattrfile` in `requirements3.txt` it works but it's dangerous or not coherent because we can't obtain this `requirements3.txt` from `requirements-to-freeze.txt`
Maybe something could be done about it in `freeze_requirements`

**Comment by thebaptiste** [comment]
If you have in `requirements-to-freeze.txt`, for example : 
`git+https://github.com/metwork-framework/directory_observer.git#egg=directory_observer`
`-e git+https://github.com/metwork-framework/xattrfile.git#egg=xattrfile`
And you run `unsafe_pip install -r requirements-to-freeze.txt`
Then `unsafe_pip freeze -l` will output, for these two lines : 
`directory-observer @ git+https://github.com/metwork-framework/directory_observer.git@cbb9020fb2643045b130159d1cf9a87edcc509bf`
`-e git+https://github.com/metwork-framework/xattrfile.git@db24341265249b3b0bf4f89604e05cea3743374b#egg=xattrfile`

I can't see any simple solution...

**Comment by thebaptiste** [comment]
By the way pip doesn't install the packages in the same place with or without `-e`
See : https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source
