### ISSUE TITLE
why we use sqlite-autoconf-3080803.tar.gz ?

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#87]
we have to understand why and probably migrate to a released version

**Comment by thebaptiste** [comment]
sqlite-autoconf-3080803.tar.gz is a released version. But on [Sqlite download page](https://www.sqlite.org/download.html) there is only a link to the last release, there are no link to old releases. That's I think the reason why we had copied the once downloaded file on metwork-framework (the file seemed to have disappeared from sqlite.org because it was no longer the last release).
To get the link of an old release, it is necessary to convert the 7 digits 3080803 in release number (it means release 3.8.8.3), go to [Sqlite Timeline](https://www.sqlite.org/src/timeline?t=release) to find the year of the release (2015 for release 3.8.8.3) and deduce the url of the old release : 
http://www.sqlite.org/2015/sqlite-autoconf-3080803.tar.gz
More explanations [here](https://stackoverflow.com/questions/615213/where-can-one-find-source-archives-of-old-sqlite-versions)

**Comment by thebaptiste** [comment]
By the way release 3.8.8.3 is an old one, the last is 3.26.0.0, released on 2018-12-01.
Maybe we should upgrade...
