### ISSUE TITLE
liquidprompt-thefab20141015.tar.gz is a derived work

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfext#88]
we have: 

- to understand why we use that instead of the official release
- migrate to an official release (or fork the repository with corresponding patches in the organization)

**Comment by thebaptiste** [comment]
liquidprompt-thefab20141015.tar.gz is a fork of originally liquidprompt master branch on 19 Jan 2014, with a little patch : redirection of `sensors` command output on /dev/null because of a CentOS5 issue (bad output of this command always in the prompt).
It seems that this problem doesn't occur in CentOS6 or 7 : first the package lm_sensors may not be installed and in this case the command will never be run; secondly, if the package is installed, the output seems to be ok.
So I think we can try to use an official release, maybe release 1.9 (16 Nov 2014, first release after the fork which occurred a few commits after release 1.8, 15 Jan 2014), or a newer version (latest version is 1.11, 25 Jun 2016, but there are some breaking changes since release 1.10).

**Comment by thebaptiste** [comment]
I have tried release 1.11 on my computer, with or without command sensors available, it seems ok (I don't see any prompt difference with "thefab" version).
