### ISSUE TITLE
Add plugin to generate test reports

### ISSUE THREAD

**Issue by lepetitnuage31** [metwork-framework/mfext#959]
Could you add the pytest-html plugin to the pytest installation in order to be able to generate the test reports?
The plugin is available at https://pypi.org/project/pytest-html/
For users of nosetest the plugin nose-html-reporting does the same service and should also be installed

**Comment by thebaptiste** [comment]
Oops, I forgot the nose plugin. I will add in in another pull request.

**Comment by thebaptiste** [comment]
For the record, nose-html-reporting has import errors on Python3 (`No module named 'StringIO'`). 
`import StringIO` must be replaced by `from io import StringIO` (cf. [here](https://stackoverflow.com/questions/28200366/python-3-x-importerror-no-module-named-cstringio))
So the usage of this nose plugin does not work in Python3...

nose-html-reporting and nose have not been released since... 2015 (no maintenership) ! nose seems to be deprecated for nose2, see [here](https://nose.readthedocs.io/en/latest/)

**Comment by thebaptiste** [comment]
So I will remove nose-html-reporting from python3_devtools layer

**Comment by lepetitnuage31** [comment]
Ok thebaptiste I will look for another solution to have the html test reports
